config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#top'
  get "home/about" => "home#about"

  resources :books, except:[:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'search#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates  :title, presence: true
  validates  :body, presence: true, length: { maximum:200 }
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true, uniqueness: {scope: :book_id}

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  # :follower → フォローする人
  # :followed → フォローされる人

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top, :about]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name, :introduction, :profile_image_id])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.find(params[:id])
    @book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "successfully"
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "successfully"
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.user.id == current_user.id
      if book.destroy
        flash[:success] = "successfully"
        redirect_to books_path
      end
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top

  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
	def create
		current_user.follow(params[:user_id])
		redirect_to request.referer
	end

	def destroy
		current_user.unfollow(params[:user_id])
		redirect_to request.referer
	end

  def followings
		@user = User.find(params[:user_id])
		@users = @user.followings
  end

  def followers
		@user = User.find(params[:user_id])
		@users = @user.followers
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Book.search_for(@content, @method)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @user_books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "successfully"
      redirect_to user_path(@user.id)
    else
      @user = User.find(params[:id])
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$('.comments').html("<%= j( render 'books/comment', book: @book) %>");
<%# escapejavascriptを省略した形がj %>
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$('.comments').html("<%= j( render 'books/comment', book: @book) %>");
<%# escapejavascriptを省略した形がj %>

app/views/books/_comment.html.erb
<p>コメント件数：<%= book.book_comments.count %></p>
<table class="comment-table">
  <tbody>
    <% book.book_comments.each do |book_comment| %>
    <tr>
      <td><%= book_comment.user.name %></td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
      <div class="comment-delete">
        <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), remote: true, method: :delete, class: "btn btn-sm btn-danger" %></td>
      </div>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<h2>New book</h2>
  <%= form_with model: book, local:true do |f| %>
    <div class="from-group">
      <label for="book_title">Title</label>
      <input class="form-control book_title" type="text" name="book[title]" id="book_title">
    </div>
    <div class="from-group">
      <label for="book_opinion">Opinion</label>
      <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
    </div>
    <div class="from-group">
      <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
    </div>
  <% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <h2>Editing Book</h2>
  <%= render 'layouts/errors', obj: @book %>

  <%= form_with model: @book, local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <p><input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" /></p>
  <% end %>
  <%= link_to "Show", book_path %> |
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>

  <div class="row">
    <div class="col-md-3">
      <%= render 'users/profile', user: current_user %>
      <div class="mt-3">
        <%= render 'books/form', book: @book %>
      </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <a href="/users/<%= book.user.id %>">
                    <%= attachment_image_tag book.user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                  </a>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <td id="favorites_buttons_<%= book.id %>">
                  <%= render 'favorites/favorite', book: book %>
                </td>
                <td>コメント数: <%= book.book_comments.count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/profile', user: @book.user %>
      <div class="mt-3">
        <%= render 'books/form', book: @book_new %>
      </div>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @book.user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %> </br>
              <%= link_to @book.user.name, "/users/#{@book.user.id}" %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
              <td id="favorites_buttons_<%= @book.id %>">
                <%= render 'favorites/favorite', book: @book %>
              </td>
            <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), :class=>"btn btn-sm btn-success edit_book_14426" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", :class=> "btn btn-sm btn-danger destroy_book_14426" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <div class="comments">
        <%= render 'books/comment', book: @book %>
      </div>

      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-75" %>
          <%= f.submit "Create Book comment" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book),remote: true, method: :delete do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book),remote: true, method: :post do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j( render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j( render 'favorites/favorite', book: @book) %>");

app/views/home/about.html.erb
<h1 class="px-3 mx-auto", style="text-align: center;">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

app/views/home/top.html.erb
<div class="top">
  <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      </div>
      <div class="row">
        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/search/search.html.erb
<% if @model == 'user' %>
	<h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'book' %>
	<h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<h2>User info</h2>
<table class="table">
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
  <thead>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user) do %>
  <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <%= render 'layouts/errors', obj: @user %>

  <h2>User info</h2>
  <%= form_with model:@user, local:true do |f| %>
    <div class="field form-item">
      <%= f.label :Name %><br />
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="field form-item">
      <%= f.label :Image %><br />
      <%= f.attachment_field :profile_image,  autofocus: true, placeholder: "プロフィール画像" %>
    </div>
    <div class="field form-item">
      <%= f.label :introduction %><br />
      <%= f.text_area :introduction, autofocus: true %>
    </div>
    <p><input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User" /></p>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/profile', user: current_user %>
      <div class="mt-3">
        <%= render 'books/form', book: @book %>
      </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <table class='table'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>フォロー数: <%= user.followings.count %></td>
              <td>フォロワー数: <%= user.followers.count %></td>
              <td>
                <% if current_user != user %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
        <thead>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>follower</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
          </tr>
          <tr>
            <th>
              <% if current_user != @user %>
                <% if current_user.following?(@user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
                <% end %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <%= link_to edit_user_path(@user) do %>
        <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
      <% end %>

      <div class="mt-3">
        <%= render 'books/form', book: @book %>
      </div>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user_books.each do |book| %>
            <tr>
              <td>
                <a  href="/users/<%= @user.id %>">
                  <%= attachment_image_tag @user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                </a>
               </td>
              <td><%= link_to book.title, book_path(book)  %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>